# Generated by Django 3.1.3 on 2021-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книжный магазин', 'verbose_name_plural': 'Книжные магазины'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
